// Generates docs/configuration.md from packages/spec/schemas/config.schema.json.
// Usage: bun scripts/docs-config.ts
// Everything outside the `<!-- manual:start -->` / `<!-- manual:end -->` markers is rendered from
// the schema; the text between the markers is read from the existing file and kept verbatim.
// Deterministic: no timestamps, properties render in schema order.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_PATH = join(ROOT, 'packages/spec/schemas/config.schema.json');
const DOCS_PATH = join(ROOT, 'docs/configuration.md');

const MANUAL_START = '<!-- manual:start -->';
const MANUAL_END = '<!-- manual:end -->';
const BANNER =
  '<!-- generated by scripts/docs-config.ts from packages/spec/schemas/config.schema.json; ' +
  'do not edit outside the manual markers. Edit the schema, then run: bun scripts/docs-config.ts -->';

type Node = Readonly<Record<string, unknown>>;

function isNode(value: unknown): value is Node {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function nodeAt(parent: Node, key: string): Node {
  const value = parent[key];
  if (!isNode(value)) throw new Error(`config schema: expected an object at "${key}"`);
  return value;
}

function entriesOf(value: unknown): [string, Node][] {
  if (!isNode(value)) return [];
  return Object.entries(value).flatMap(([key, child]) => (isNode(child) ? [[key, child]] : []));
}

function nodesOf(value: unknown): Node[] {
  return Array.isArray(value) ? value.filter(isNode) : [];
}

function text(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function cell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function literal(value: unknown): string {
  return typeof value === 'string' ? `'${value}'` : String(value);
}

/** The schema title, or the `$defs` key when a definition has none. */
function refName(ref: string, defs: Node): string {
  const key = ref.slice('#/$defs/'.length);
  const def = defs[key];
  return (isNode(def) ? text(def.title) : '') || key;
}

function rangeOf(schema: Node, kind: 'number' | 'integer'): string {
  const min = schema['minimum'];
  const max = schema['maximum'];
  if (typeof min === 'number' && typeof max === 'number') return `${kind} (${min}..${max})`;
  if (typeof min === 'number') return `${kind} (>= ${min})`;
  return kind;
}

function typeOf(schema: Node, defs: Node): string {
  const ref = schema['$ref'];
  if (typeof ref === 'string') return `\`${refName(ref, defs)}\``;
  if ('const' in schema) return `\`${literal(schema['const'])}\``;
  const alternatives = Array.isArray(schema['enum'])
    ? schema['enum'].map((v) => `\`${literal(v)}\``)
    : nodesOf(schema['anyOf']).map((s) => typeOf(s, defs));
  if (alternatives.length > 0) return `one of: ${alternatives.join(' | ')}`;
  const type = schema['type'];
  switch (type) {
    case 'number':
    case 'integer':
      return `\`${rangeOf(schema, type)}\``;
    case 'array':
      return `array of ${isNode(schema['items']) ? typeOf(schema['items'], defs) : '`unknown`'}`;
    case 'object':
      return objectType(schema, defs);
    default:
      return `\`${text(schema['type']) || 'unknown'}\``;
  }
}

function objectType(schema: Node, defs: Node): string {
  const extra = schema['additionalProperties'];
  if (isNode(extra) && Object.keys(extra).length === 0) return '`object (any keys)`';
  if (isNode(extra) && !('properties' in schema)) {
    const values = nodesOf(extra['anyOf']);
    const target =
      values.length > 0 ? values.map((s) => typeOf(s, defs)).join(' | ') : typeOf(extra, defs);
    return `map of name → ${target}`;
  }
  return '`object`';
}

/** The `properties` of a schema, or of the object branches of its `anyOf`. */
function fieldsOf(schema: Node): { fields: [string, Node][]; required: Set<string> } {
  const sources = [schema, ...nodesOf(schema['anyOf'])];
  const fields = sources.flatMap((s) => entriesOf(s['properties']));
  const required = new Set(
    sources.flatMap((s) =>
      Array.isArray(s['required']) ? s['required'].filter((r) => typeof r === 'string') : [],
    ),
  );
  return { fields, required };
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string[] {
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ];
}

function fieldTable(schema: Node, defs: Node): string[] {
  const { fields, required } = fieldsOf(schema);
  if (fields.length === 0) return [];
  return [
    ...table(
      ['Field', 'Type', 'Required', 'Description'],
      fields.map(([name, field]) => [
        `\`${name}\``,
        cell(typeOf(field, defs)),
        required.has(name) ? 'yes' : 'no',
        cell(text(field['description'])) || '—',
      ]),
    ),
    '',
  ];
}

function section(name: string, schema: Node, defs: Node): string[] {
  const description = text(schema['description']);
  return [
    `### ${name}`,
    '',
    ...(description === '' ? [] : [description, '']),
    `Type: ${typeOf(schema, defs)}`,
    '',
    ...fieldTable(schema, defs),
  ];
}

/** Renders docs/configuration.md; `manual` is the text between the manual markers. */
export function renderConfigDocs(schema: unknown, manual: string): string {
  if (!isNode(schema)) throw new Error('config schema: root must be an object');
  const defs = nodeAt(schema, '$defs');
  const properties = nodeAt(schema, 'properties');
  const required = new Set(Array.isArray(schema['required']) ? schema['required'] : []);
  const keys = entriesOf(properties);
  const lines = [
    BANNER,
    '',
    '# Configuration',
    '',
    text(schema['description']),
    '',
    '## Keys',
    '',
    ...table(
      ['Key', 'Type', 'Required', 'Description'],
      keys.map(([key, property]) => [
        `\`${key}\``,
        cell(typeOf(property, defs)),
        required.has(key) ? 'yes' : 'no',
        cell(text(property['description'])) || '—',
      ]),
    ),
    '',
    ...keys.flatMap(([key, property]) => section(key, property, defs)),
    '## Shapes',
    '',
    ...entriesOf(defs).flatMap(([key, shape]) => section(text(shape['title']) || key, shape, defs)),
    MANUAL_START,
    manual,
    MANUAL_END,
    '',
  ];
  return lines.join('\n');
}

function extractManual(content: string): string | undefined {
  const start = content.indexOf(MANUAL_START);
  const end = content.indexOf(MANUAL_END);
  if (start === -1 || end === -1 || end < start) return undefined;
  return content.slice(start + MANUAL_START.length + 1, end - 1);
}

if (import.meta.main) {
  // Reading the repo's own schema: the raw JSON.parse ban is scoped to packages/*/src.
  const schema: unknown = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8'));
  let existing = '';
  try {
    existing = readFileSync(DOCS_PATH, 'utf8');
  } catch {
    // no docs file yet
  }
  const manual = extractManual(existing);
  if (manual === undefined) {
    process.stderr.write('docs-config: no manual region found; writing an empty one\n');
  }
  writeFileSync(DOCS_PATH, renderConfigDocs(schema, manual ?? ''));
}
